### ISSUE TITLE
TAPAS with mouse genome

### ISSUE THREAD

**Issue by rikaiese** [arefeen/TAPAS#1]
Hello,
I would like to use your tool with RNA-seq data from mouse samples. Could you give me an indication on the format/requirements of the annotation file? I have the ENSEMBL GTF/GFF files and with your indications I could modify it to make it work with TAPAS.
Thank you for your help
Riccardo

**Comment by arefeen** [comment]
Sorry for the late reply.
The tool takes refFlat annotation file (UCSC) as input. A sample file (refFlat_sf.txt) is given in the 'sample' directory. Please have a look to understand the file format.
