### ISSUE TITLE
Samtools or deptools

### ISSUE THREAD

**Issue by JamalEH** [arefeen/TAPAS#8]
Hi,

I tried to follow your pipeline to get the read coverage using samtools, but did not work. I got the following error: unrecognized command 'coverage'

Could you plase specify the command and options used to get the read coverage of each bam file?
Can I use bedtools genomecov instead? or samtools depth, in default options?

Thank you in advance!
Kind regards,
Jamal.

**Comment by arefeen** [comment]
Hi Jamal,

There is a "Useful Commands" section in the github page. Try to follow the commands to generate the coverage file from bam file. Use the coverage file to run the tool.

Thanks,
Ashraful

**Comment by JamalEH** [comment]
Hi dear,
Thank you for your reply!

Indeed, everything is well explained in the code page and the paper. 
Sorry for that.

Kind regards,
Jamal.
